### ISSUE TITLE
Recherche AssetStore : Framework de platforming

### ISSUE THREAD

**Issue by graslany** [cmia11/PermisDeVoyage#3]
Exigences :
* Avoir les sources
* Pouvoir composer un niveau comme une grille où on met des cases (les plateformes n'ont pas des formes arbitraires).
* Pouvoir rendre une case qui se déplace (déplacer l'image continument)
* Pouvoir dans une scène, sans toucher au code et sans connaître les concepts Unity (GameObjects, composants, etc.) :
  * définir quelles textures on veut utiliser pour le fond, le sol, etc.
  * définir la taille d'un niveau et le peupler avec des cases

Valider en créant le premier niveau qu'on a imaginé (sans chercher à pousser la caisse pour l'instant).

**Comment by JoanSivion** [comment]
Les composants 2D d'Unity semblent remplir nativement les différents critères.
En particulier, le concept de Tilemap permet de composer des niveaux à la main à partir de différents sprites. Un tutorial rapide et clair : https://www.raywenderlich.com/23-introduction-to-the-new-unity-2d-tilemap-system

**Comment by JoanSivion** [comment]
Tutoriel vidéo officiel de Unity : https://www.youtube.com/watch?v=tDX2ChhntD8&list=PLX2vGYjWbI0RX4rWxhg15UJ9GGf3tFLNQ&index=1
